//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contents_CategoryLevel1
    {
        public int ID { get; set; }
        public string CodeContents { get; set; }
        public string CodeCategoryLevel1 { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> Disable { get; set; }
        public Nullable<int> IDLang { get; set; }
    }
}
