//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contents
    {
        public int ID { get; set; }
        public Nullable<int> Type { get; set; }
        public string Title { get; set; }
        public string Info { get; set; }
        public string Intro { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> Disable { get; set; }
        public string Tag { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Image { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public Nullable<int> IDAlbum { get; set; }
        public Nullable<int> IDLang { get; set; }
        public string Code { get; set; }
        public string ExtendProperties1 { get; set; }
        public string ExtendProperties2 { get; set; }
        public string ExtendProperties3 { get; set; }
        public Nullable<long> ViewCount { get; set; }
        public byte[] Data { get; set; }
        public Nullable<long> Vote { get; set; }
        public Nullable<long> CommentCount { get; set; }
        public Nullable<long> LikeCount { get; set; }
    }
}
