//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendProperties
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<int> ValueType { get; set; }
        public string Image { get; set; }
        public string Code { get; set; }
        public Nullable<int> IDObject { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> IDLang { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Group { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CodeObject { get; set; }
        public Nullable<bool> Disable { get; set; }
    }
}
