//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ContentViewAll
    {
        public string Contents_UpdateBy { get; set; }
        public Nullable<int> Contents_Type { get; set; }
        public Nullable<System.DateTime> Contents_PublishDate { get; set; }
        public string Contents_Title { get; set; }
        public Nullable<System.DateTime> Contents_ExpireDate { get; set; }
        public string Contents_Info { get; set; }
        public string Contents_Image { get; set; }
        public Nullable<int> Contents_Status { get; set; }
        public string Contents_CreatedBy { get; set; }
        public Nullable<bool> Contents_Disable { get; set; }
        public Nullable<System.DateTime> Contents_DateCreated { get; set; }
        public Nullable<System.DateTime> Contents_DateEdited { get; set; }
        public Nullable<long> Contents_ViewCount { get; set; }
        public int Contents_ID { get; set; }
        public string Contents_Code { get; set; }
        public Nullable<int> Contents_CategoryLevel1_Status { get; set; }
        public Nullable<int> Contents_CategoryLevel1_Type { get; set; }
        public Nullable<bool> Contents_CategoryLevel1_Disable { get; set; }
        public string CategoryLevel1_CategoryNameLevel1 { get; set; }
        public Nullable<int> CategoryLevel1_Status { get; set; }
        public Nullable<bool> CategoryLevel1_Disable { get; set; }
        public string CategoryLevel1_Code { get; set; }
        public Nullable<int> CategoryLevel1_Type { get; set; }
        public Nullable<long> CategoryLevel1_ViewCount { get; set; }
        public Nullable<int> Contents_CategoryLevel1_IDLang { get; set; }
        public Nullable<long> Contents_Vote { get; set; }
        public Nullable<long> Contents_CommentCount { get; set; }
        public Nullable<long> Contents_LikeCount { get; set; }
        public string Contents_Intro { get; set; }
    }
}
