//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CategoryLevel1ViewAll
    {
        public int CategoryLevel1_ID { get; set; }
        public string CategoryLevel1_CategoryNameLevel1 { get; set; }
        public Nullable<int> CategoryLevel1_Status { get; set; }
        public Nullable<bool> CategoryLevel1_Disable { get; set; }
        public string CategoryLevel1_Code { get; set; }
        public Nullable<int> CategoryLevel1_Type { get; set; }
        public string CategoryLevel1_Image { get; set; }
        public string CategoryLevel1_Info { get; set; }
        public Nullable<long> CategoryLevel1_ViewCount { get; set; }
        public Nullable<int> CategoryLevel1_CategoryLevel2_Status { get; set; }
        public Nullable<int> CategoryLevel1_CategoryLevel2_Type { get; set; }
        public Nullable<bool> CategoryLevel1_CategoryLevel2_Disable { get; set; }
        public Nullable<int> CategoryLevel1_CategoryLevel2_ID { get; set; }
        public Nullable<int> CategoryLevel2_ID { get; set; }
        public string CategoryLevel2_CategoryNameLevel2 { get; set; }
        public Nullable<int> CategoryLevel2_Status { get; set; }
        public Nullable<bool> CategoryLevel2_Disable { get; set; }
        public string CategoryLevel2_Code { get; set; }
        public Nullable<int> CategoryLevel1_CategoryLevel2_IDLang { get; set; }
        public string CountContent { get; set; }
        public string CountContentEnable { get; set; }
        public string CountContentDisable { get; set; }
    }
}
