//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FilesViewAll
    {
        public int Albums_ID { get; set; }
        public string Albums_Title { get; set; }
        public Nullable<int> Albums_Status { get; set; }
        public Nullable<bool> Albums_Disable { get; set; }
        public string Albums_Image { get; set; }
        public Nullable<int> Albums_Type { get; set; }
        public int Files_ID { get; set; }
        public string Files_Image { get; set; }
        public Nullable<System.DateTime> Files_UploadDate { get; set; }
        public Nullable<long> Files_CreateByIDUser { get; set; }
        public Nullable<int> Files_Status { get; set; }
        public Nullable<int> Files_Type { get; set; }
        public Nullable<bool> Files_Disable { get; set; }
        public Nullable<int> Files_IDLang { get; set; }
        public string Files_Code { get; set; }
        public Nullable<long> Files_ViewCount { get; set; }
        public Nullable<long> Files_DownloadCount { get; set; }
        public string Files_Title { get; set; }
        public string Files_Intro { get; set; }
        public string Albums_Code { get; set; }
    }
}
