//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PermitViewAll
    {
        public int SystemUsers_ID { get; set; }
        public string SystemUsers_Username { get; set; }
        public Nullable<int> SystemUsers_UserGroup { get; set; }
        public Nullable<int> SystemUsers_Status { get; set; }
        public string SystemUsers_Email { get; set; }
        public Nullable<int> SystemUsers_Type { get; set; }
        public Nullable<bool> SystemUsers_Disable { get; set; }
        public Nullable<bool> Permits_SystemUsers_IsView { get; set; }
        public Nullable<bool> Permits_SystemUsers_IsUpdate { get; set; }
        public Nullable<bool> Permits_SystemUsers_IsDelete { get; set; }
        public Nullable<bool> Permits_SystemUsers_IsInsert { get; set; }
        public Nullable<bool> Permits_SystemUsers_IsSpecial { get; set; }
        public string Permits_SystemUsers_Description { get; set; }
        public Nullable<int> Permits_SystemUsers_Status { get; set; }
        public Nullable<bool> Permits_SystemUsers_Disable { get; set; }
        public Nullable<int> Permits_SystemUsers_Type { get; set; }
        public int Permits_ID { get; set; }
        public Nullable<bool> Permits_IsContent { get; set; }
        public Nullable<bool> Permits_IsPartner { get; set; }
        public string Permits_SystemKey { get; set; }
        public Nullable<bool> Permits_Disable { get; set; }
        public Nullable<int> Permits_Type { get; set; }
        public Nullable<int> Permits_Status { get; set; }
        public string Permits_Name { get; set; }
        public string PermitDetails_Name { get; set; }
        public string PermitDetails_PageURL { get; set; }
        public Nullable<int> PermitDetails_Status { get; set; }
        public int PermitDetails_ID { get; set; }
        public Nullable<int> PermitDetails_Type { get; set; }
        public Nullable<bool> PermitDetails_Disable { get; set; }
    }
}
